#' CalculateEBEffectSize
#'
#' This function performs the entire Empirical-Bayes estimation of effect sizes
#' workflow as outlined in step2 of the vignette
#' @param bfile description
#' @param plink2_exec description
#' @param prs_tune description
#' @param results_dir description
#' @param out_prefix description
#' @param plink_list description
#' @param memory description
#' @param threads description
#' @param params_farm list of parameters generated by SetClumpFarm().
#' @keywords plink1.9 clump
#' @export

EBayesEffectSize <- function(bfile,
                             prs_tune,
                             plink_list,
                             memory = 8000,
                             threads = 2,
                             out_prefix,
                             results_dir,
                             params_farm = as.null()){
  print("Executing EBayesEffectSize() ... ")
  scores <- plink_list[[1]]
  clump_info <- plink_list[[3]]

  best_snps <- colnames(prs_tune)[max_ind+2]
  best_snp_set <- GetSNPSet(snp_ind = best_snps,
                            scores = scores,
                            clump_info = clump_info)

  clump_info_post <- EBayesPostMean(clump_info = clump_info,
                                    snp_set = best_snp_set)
  post_coef_mat <- cbind(clump_info_post$BETA_EB_target,
                         clump_info_post$BETA_EB_ref)
  colnames(post_coef_mat) <- c("EB_target","EB_ref")

  plinklist_eb <- PreparePlinkFileEBayes(snp_list = snp_list,
                                          clump_info = clump_info,
                                          post_clump_info = clump_info_post,
                                          post_beta = post_coef_mat,
                                          results_dir = results_dir)

  assign("best_snps", best_snp_set, envir = .GlobalEnv)
  assign("unique_infor_post", clump_info_post, envir = .GlobalEnv)
  assign("plink_list_eb", plinklist_eb, envir = .GlobalEnv)

  scores_eb <- plinklist_eb[[1]]
  score_eb_file <- as.character(unlist(plinklist_eb["score_eb_file"]))
  write.table(scores_eb,
              file = score_eb_file,
              row.names = F,
              col.names = F,
              quote=F)
  p_values_eb <- plinklist_eb[[2]]

  ebayes_prs <- PRSscoreEBayes(bfile = bfile,
                               eb_plink_list = plinklist_eb,
                               plink_list = plink_list,
                               results_dir = results_dir,
                               out_prefix = outprefix,
                               params_farm = params_farm)

  assign("scores_eb", scores_eb, envir = .GlobalEnv)
  assign("score_eb_file", score_eb_file, envir = .GlobalEnv)
  assign("p_values_eb", p_values_eb, envir = .GlobalEnv)

  return(prs_mat_eb)

}

