#' dimCT
#'
#' This function performs the entire two-dimensional clumping and thresholding
#' workflow (dimCT) as outlined in step1 of the vignette
#' @param plink19_exec Plink binary execute file. Default "plink".
#' @param sum_ref
#' @param sum_target
#' @param ref_plink
#' @param target_plink
#' @param ref_split_file
#' @param target_split_file
#' @param ref_clump_out
#' @param target_clump_out
#' @param clump_farm list of parameters generated by SetClumpFarm().
#' @keywords plink1.9 clump
#' @usage dimCT(plink19_exec, clump_farm)
#' @export
#' @examples
#' data.dir <- "data/"
#' temp.dir <- test/temp.dir
#' system("mkdir -p test/temp.dir")
#' sum_EUR <- fread(paste0(data.dir,"EUR_sumdata.txt"),header=T)
#' sum_AFR <- fread(paste0(data.dir,"AFR_sumdata.txt"),header=T)
#' Eur_plinkfile <- paste0(data.dir,"EUR_ref_chr22")
#' Afr_plinkfile <- paste0(data.dir,"AFR_ref_chr22")
#' ref_out <- "test/temp/ref",
#' target_out <- "test/temp/target"
#' clump_farm <- SetClumpFarm(plink19exec = /Apps/plink1.9/plink,
#'                            wc_base_vec = c(50,100),
#'                            r2_vec = c(0.01,0.05,0.1,0.2,0.5,0.8),
#'                            threads = 2,
#'                            mem = 8000,
#' )
#' dimCT(plink19_exec=plink19_exec,
#'       sum_target = sum_AFR,
#'       sum_ref = sum_EUR,
#'       ref_plink=ref_plink,
#'       target_plink=target_plink,
#'       ref_clump_out=ref_clump_out,
#'       target_clump_out=target_clump_out,
#'       clump_farm)

dimCT <- function(plink19_exec = 'plink',
                  sum_ref,
                  sum_target,
                  ref_plink,
                  target_plink,
                  ref_split_file,
                  target_split_file,
                  ref_clump_out = 'ref',
                  target_clump_out = 'target',
                  clump_farm) {
  r2_vec <- as.vector(unlist(clump_farm["r2_vec"]))
  wc_base_vec <- as.vector(unlist(clump_farm["wc_base_vec"]))
  mem <- as.character(unlist(clump_farm["mem"]))
  #temp.dir <- as.character(unlist(clump_farm["temp_dir"]))
  #ref_plink <- as.character(unlist(clump_farm["ref_plink"]))
  #target_plink <- as.character(unlist(clump_farm["target_plink"]))
  threads <- as.character(unlist(clump_farm["threads"]))
  #ref_split_file <- as.character(unlist(clump_farm["ref_split_file"]))
  #target_split_file <- as.character(unlist(clump_farm["target_split_file"]))
  AlignSum(sum_target = sum_AFR,
           sum_ref = sum_EUR,
           ref_split_file = ref_split_file,
           target_split_file = target_split_file,
           SplitSum = TRUE)

  snp_list <-list()
  temp <- 1
  for(r_ind in 1:length(r2_vec)){
    wc_vec <- wc_base_vec/r2_vec[r_ind]
    for(w_ind in 1:length(wc_vec)){
      pthr <-1
      r2thr <- r2_vec[r_ind]
      kbpthr <- wc_vec[w_ind]
      ref_outfile <- paste0(ref_clump_out, "_CT_rind_",r_ind,"_wcind_",w_ind)
      target_outfile <- paste0(target_clump_out, "_CT_rind_",r_ind,"_wcind_",w_ind)
      Plink19Clump(plink19_exec = plink19_exec,
                         bfile = ref_plink,
                         clump = ref_split_file,
                         clump_p1 = pthr,
                         clump_r2 = r2thr,
                         clump_kb = kbpthr,
                         threads = threads,
                         memory = mem,
                         out = ref_outfile
      )
      Plink19Clump(plink19_exec = plink19_exec,
                         bfile = target_plink,
                         clump = target_split_file,
                         clump_p1 = pthr,
                         clump_r2 = r2thr,
                         clump_kb = kbpthr,
                         threads = threads,
                         memory = mem,
                         out = target_outfile
      )
      LD_ref <-fread(paste0(ref_outfile,
                            ".clumped"))[,3,drop=F]
      LD_target <-fread(paste0(target_outfile,
                               ".clumped"))[,3,drop=F]
      print(paste0("binding rows for ",
                   ref_outfile,
                   ".clumped and ",
                   target_outfile,
                   ".clumped"))
      LD  <- rbind(LD_ref,LD_target)
      snp_list[[temp]] <- LD
      print(paste0("creating snp list for clump_r2_",
                   r2thr,
                   "_ws_",
                   kbpthr))
      names(snp_list[[temp]]) <- paste0("clump_r2_",
                                        r2thr,
                                        "_ws_",
                                        kbpthr)
      temp <- temp + 1
    }
  }
  #return(snp_list)
}
