#' dimCT
#'
#' This function performs the entire two-dimensional clumping and thresholding
#' workflow (dimCT) as outlined in step1 of the vignette
#' @param plink19_exec Plink binary execute file. Default "plink".
#' @param sum_ref
#' @param sum_target
#' @param ref_plink
#' @param target_plink
#' @param ref_split_file
#' @param target_split_file
#' @param ref_clump_out
#' @param target_clump_out
#' @param params_farm list of parameters generated by SetClumpFarm().
#' @keywords plink1.9 clump
#' @usage dimCT(plink19_exec, params_farm)
#' @export
#' @examples
#' data.dir <- "data/"
#' temp.dir <- test/temp.dir
#' system("mkdir -p test/temp.dir")
#' sum_EUR <- fread(paste0(data.dir,"EUR_sumdata.txt"),header=T)
#' sum_AFR <- fread(paste0(data.dir,"AFR_sumdata.txt"),header=T)
#' ref_split_file <- paste0(temp.dir,"sum_ref.txt")
#' target_split_file <- paste0(temp.dir,"sum_target.txt")
#' Eur_plinkfile <- paste0(data.dir,"EUR_ref_chr22")
#' Afr_plinkfile <- paste0(data.dir,"AFR_ref_chr22")
#' ref_out <- "test/temp/ref",
#' target_out <- "test/temp/target"
#' params_farm <- SetParamsFarm(plink19exec = /Apps/plink1.9/plink,
#'                            wc_base_vec = c(50,100),
#'                            r2_vec = c(0.01,0.05,0.1,0.2,0.5,0.8),
#'                            threads = 2,
#'                            mem = 8000,
#' )
#' dimCT(plink19_exec=plink19_exec,
#'       sum_target = sum_AFR,
#'       sum_ref = sum_EUR,
#'       ref_plink= Eur_plinkfile,
#'       target_plink= Afr_plinkfile,
#'       ref_split_file = ref_split_file,
#'       target_split_file = target_split_file,
#'       ref_clump_out=ref_out,
#'       target_clump_out=target_out,
#'       params_farm = params_farm)

dimCT <- function(plink19_exec = 'plink',
                  plink2_exec = 'plink',
                  results_dir = "./",
                  sum_target,
                  sum_ref,
                  ref_plink,
                  target_plink,
                  out_prefix = as.null(),
                  r2_vec = c(0.01,0.05,0.1,0.2,0.5,0.8),
                  wc_base_vec = c(50,100),
                  scores,
                  p_values,
                  mem = 8000,
                  threads = 2,
                  params_farm = as.null()) {
  # if (is.null(params_farm)) {
  #   print("no params_farm")
  # } else {
  #   print("params_farm list will be used")
  #   plink19_exec <- as.character(unlist(params_farm["plink19_exec"]))
  #   r2_vec <- as.vector(unlist(params_farm["r2_vec"]))
  #   wc_base_vec <- as.vector(unlist(params_farm["wc_base_vec"]))
  #   mem <- as.character(unlist(params_farm["mem"]))
  #   threads <- as.character(unlist(params_farm["threads"]))
  # }

  AlignSum(sum_target = sum_AFR,
           sum_ref = sum_EUR,
           results_dir = results_dir,
           SplitSum = TRUE)

  RunClump(params_farm = params_farm,
           plink19_exec = plink19_exec,
           ref_plink = ref_plink,
           target_plink = target_plink,
           out_prefix = out_prefix,
           results_dir = results_dir)

  # print("executing PreparePlinkFile()")
  # PreparePlinkFile(params_farm = params_farm,
  #                  snp_list = snp_list,
  #                  sum_com = sum_com,
  #                  results_dir = results.dir,
  #                  return_list = FALSE)
  # print("executing PRSscore()")
  # PRSscore(params_farm = params_farm,
  #          plink2_exec = plink2_exec,
  #          bfile = target_plink,
  #          scores = scores,
  #          p_values = p_values,
  #          threads = 4,
  #          memory = 8000,
  #          results_dir = results_dir)

}
