#' dimCT
#'
#' This function performs the entire two-dimensional clumping and thresholding
#' workflow (dimCT) as outlined in step1 of the vignette
#' @param plink19_exec Plink binary execute file. Default "plink".
#' @param plink2_exec
#' @param results_dir
#' @param sum_ref
#' @param sum_target
#' @param ref_plink
#' @param target_plink
#' @param test_target_plink,
#' @param out_prefix
#' @param r2_vec
#' @param wc_base_vec
#' @param memory
#' @param threads
#' @param params_farm list of parameters generated by SetClumpFarm().
#' @keywords plink1.9 clump
#' @usage dimCT(plink19_exec, params_farm)
#' @export
#' @examples
#' data.dir <- "data/"
#' temp.dir <- test/temp.dir
#' system("mkdir -p test/temp.dir")
#' sum_EUR <- fread(paste0(data.dir,"EUR_sumdata.txt"),header=T)
#' sum_AFR <- fread(paste0(data.dir,"AFR_sumdata.txt"),header=T)
#' ref_split_file <- paste0(temp.dir,"sum_ref.txt")
#' target_split_file <- paste0(temp.dir,"sum_target.txt")
#' Eur_plinkfile <- paste0(data.dir,"EUR_ref_chr22")
#' Afr_plinkfile <- paste0(data.dir,"AFR_ref_chr22")
#' ref_out <- "test/temp/ref",
#' target_out <- "test/temp/target"
#' params_farm <- SetParamsFarm(plink19exec = /Apps/plink1.9/plink,
#'                            wc_base_vec = c(50,100),
#'                            r2_vec = c(0.01,0.05,0.1,0.2,0.5,0.8),
#'                            threads = 2,
#'                            mem = 8000,
#' )
#' dimCT(plink19_exec=plink19_exec,
#'       sum_target = sum_AFR,
#'       sum_ref = sum_EUR,
#'       ref_plink= Eur_plinkfile,
#'       target_plink= Afr_plinkfile,
#'       ref_split_file = ref_split_file,
#'       target_split_file = target_split_file,
#'       ref_clump_out=ref_out,
#'       target_clump_out=target_out,
#'       params_farm = params_farm)

dimCT <- function(plink19_exec = 'plink',
                  plink2_exec = 'plink',
                  results_dir = "./",
                  sum_target,
                  sum_ref,
                  ref_plink,
                  target_plink,
                  test_target_plink,
                  out_prefix = as.null(),
                  r2_vec = c(0.01,0.05,0.1,0.2,0.5,0.8),
                  wc_base_vec = c(50,100),
                  memory= 8000,
                  threads = 2,
                  params_farm = as.null()) {

  if (is.null(params_farm)) {
    print("no params_farm")
  } else {
    print("params_farm list will be used")
    plink19_exec <- as.character(unlist(params_farm["plink19_exec"]))
    plink2_exec <-  as.character(unlist(params_farm["plink2_exec"]))
    r2_vec <- as.numeric(unlist(params_farm["r2_vec"]))
    wc_base_vec <- as.integer(unlist(params_farm["wc_base_vec"]))
    memory <- as.integer(unlist(params_farm["mem"]))
    threads <- as.integer(unlist(params_farm["threads"]))
    pthres <- as.numeric(unlist(params_farm["pthres"]))
  }

  sum.com <- AlignSum(sum_target = sum_AFR,
                      sum_ref = sum_EUR)
  assign("sum_com", sum.com, envir = .GlobalEnv)
  write.list <- SplitSum(x = sum.com,
                         results_dir = results_dir,
                         write_tables = TRUE)
  assign("write_list", write.list, envir = .GlobalEnv)

  ref.splitfile <- unlist(write.list["ref_split_file"])
  target.splitfile <- unlist(write.list["target_split_file"])
  snp.list <- RunClump(params_farm = params_farm,
                       plink19_exec = plink19_exec,
                       ref_plink = ref_plink,
                       target_plink = target_plink,
                       ref_splitfile = ref.splitfile,
                       target_splitfile = target.splitfile,
                       out_prefix = out_prefix,
                       results_dir = results_dir)
  assign("snp_list", snp.list, envir = .GlobalEnv)


  plink.list <- PreparePlinkFile(params_farm = params_farm,
                                  snp_list = snp.list,
                                  sum_com = sum.com,
                                  results_dir = results_dir)

  file_list <- helper_PreparePlinkFile(plink_list = plink.list,
                                       results_dir = results_dir)
  plink.list <- c(plink.list,file_list)
  assign("plink_list", plink.list, envir = .GlobalEnv)

  prs_mat <- PRSscore(params_farm = params_farm,
                      plink2_exec = plink2_exec,
                      bfile = test_target_plink,
                      plink_list = plink.list,
                      threads = threads,
                      memory = memory,
                      out_prefix = out_prefix,
                      results_dir = results_dir)
  assign("prs_mat", prs_mat, envir = .GlobalEnv)
  return(prs_mat)
}
