#' Helper function for PRSscore()
#'
#' This function iterates the plink2score function through pthres and p_values
#' @param plink2_exec Plink binary execute file. Default "plink2".
#' @param bfile prefix for target plink binary set (prefix.bed, prefix.bim, prefix.fam)
#' @param q_range_file File name and location of written q_range dataframe produced
#' by PreparePlinkfile(). By default PreparePlinkfile() names this 'q_range_file'
#' @param score_col_nums number of columns in scores dataframe produced by
#' PreparePlinkfile().
#' @param scores_file File name and location of written scores dataframe produced
#' by PreparePlinkfile(). By default PreparePlinkfile() names this 'scores_file'
#' @param p_values p_values dataframe produced by PreparePlinkfile()
#' @param pthres vector of p_value thresholds used to select snps for PRS.
#' Default vector name is 'pthres' which is generated by PreparePlinkfile()
#' @param threads maximum number of concurrent threads
#' @param memory primary workspace memory
#' @param out Plink2 out file prefix. Default name prs_p_other_
#' <pthres column number>.<range name>.sscore
#' @keywords plink2 score
#' @usage Plink19Clump(plink2_exec, bfile, q_score_range, score_col_nums,
#' score, threads, memory, out, params_farm)
#' @examples
#' PRSscore(plink2_exec = "plink2 ",
#'             bfile = bfile,
#'             q_range_file = q_range_file,
#'             score_col_nums = ncols,
#'             scores_file = scores_file,
#'             p_values = p_values,
#'             pthres = pthres,
#'             threads = 4,
#'             memory = 8000,
#'             out,
#'             params_farm = params_farm)

helper_score_loop <- function(plink2_exec,
                        bfile,
                        q_range_file = q_range_file,
                        p_value_file = p_value_file,
                        score_col_nums,
                        scores_file = scores_file,
                        p_values = p_values,
                        pthres = pthres,
                        threads = threads,
                        memory = mem,
                        results_dir = results_dir,
                        params_farm = params_farm){

  if (is.null(params_farm)) {
    print("no params_farm")
  } else {
    print("params_farm list will be used")
    mem <- as.character(unlist(params_farm["mem"]))
    threads <- as.character(unlist(params_farm["threads"]))
    pthres <- as.character(unlist(params_farm["pthres"]))
  }

  prs_prefix <- "prs_p_other_"
  p_values_temp <- p_values
  p_value_file <- paste0(temp.dir,"p_value_file")
  for(k1 in 1:length(pthres)){
    #keep all the SNPs with P_EUR less than pthres[k1] in the analyses
    idx <- which(unique_infor$P_ref<=pthres[k1])
    p_values_temp$P[idx] <- 0
    write.table(p_values_temp,
                file = p_value_file,
                col.names = F,
                row.names = F,
                quote=F)
    temp.dir <- paste0(results_dir,"temp/")
    out_file <- paste0(temp.dir,prs_prefix,k1)
    plink2score(params_farm = params_farm,
                plink2_exec = plink2_exec,
                bfile = AFR_plinkfile,
                q_range_file = q_range_file,
                p_value_file = p_value_file,
                score_col_nums = score_col_nums,
                scores_file = scores_file,
                threads = 4,
                memory = 8000,
                out = out_file)
  }
}
