#' Helper function for PRSscore()
#'
#' This function iterates the plink2score function through pthres and p_values
#' @param plink2_exec Plink binary execute file. Default "plink2".
#' @param bfile prefix for target plink binary set (prefix.bed, prefix.bim, prefix.fam)
#' @param ebayes
#' @param plink_list
#' @param pthres vector of p_value thresholds used to select snps for PRS.
#' Default vector name is 'pthres' which is generated by PreparePlinkfile()
#' @param threads maximum number of concurrent threads
#' @param memory primary workspace memory
#' @param results_dir
#' @param out_prefix
#' @param params_farm params_farm object name
#' @keywords plink2 score
#' @usage Plink19Clump(plink2_exec, bfile, q_score_range, score_col_nums,
#' score, threads, memory, out, params_farm)

helper_score_loop <- function(plink2_exec,
                        bfile,
                        plink_list,
                        pthres,
                        threads,
                        memory,
                        results_dir,
                        params_farm = as.null(),
                        out_prefix = as.null()){

  if (is.null(params_farm)) {
    print("no params_farm")
  } else {
    print("params_farm list will be used")
    plink2_exec <- unlist(params_farm["mem"])
    memory <- as.integer(unlist(params_farm["mem"]))
    threads <- as.integer(unlist(params_farm["threads"]))
    pthres <- as.numeric(unlist(params_farm["pthres"]))
  }

  temp.dir <- paste0(results_dir,"temp/")
  out.prefix <- helper_prefix(out_prefix = out_prefix,
                                  ebayes = FALSE)

  scores <- plink_list[[1]]
  p_values <- plink_list[[2]]
  unique_infor <- plink_list[[3]]
  p_value_file <- as.character(unlist(plink_list["p_value_file"]))
  score_file <- as.character(unlist(plink_list["score_file"]))
  q_range_file <- as.character(unlist(plink_list["q_range_file"]))
  prs_p_other_ <- paste0(temp.dir, out.prefix, "prs_p_other_")
  pthres <- pthres
  assign("prs_p_other_", prs_p_other_, envir = .GlobalEnv)
  p_values_temp <- p_values

  for(k1 in 1:length(pthres)){
    idx <- which(unique_infor$P_ref <= pthres[k1])
    #print(unique_infor$P_ref[1:20])
    #print(str(unique_infor))
    print(paste0("pthres: ", pthres[k1]))
    print(class(pthres[k1]))
    #print(idx[1:20])
    p_values_temp$P[idx] <- 0
    print(paste0("Number of variants less than pthres :",
                 sum(p_values_temp$P == 0)))
    print(paste0("writing ", p_value_file))
    write.table(p_values_temp,
                file = p_value_file,
                col.names = F,
                row.names = F,
                quote=F)
    score.col_nums <- ncol(scores)
    plink2score(plink2_exec = plink2_exec,
                bfile = bfile,
                q_range_file = q_range_file,
                p_value_file = p_value_file,
                score_file = score_file,
                score_col_nums = score.col_nums,
                results_dir = results_dir,
                pthres_idx = k1,
                threads = threads,
                out = prs_p_other_,
                memory = memory)
  }
  return(prs_p_other_)
}
