#' Helper function for PRSscore()
#'
#' This function iterates the plink2score function through pthres and p_values
#' @param plink2_exec Plink binary execute file. Default "plink2".
#' @param bfile prefix for target plink binary set (prefix.bed, prefix.bim, prefix.fam)
#' @param plink_list
#' @param pthres vector of p_value thresholds used to select snps for PRS.
#' Default vector name is 'pthres' which is generated by PreparePlinkfile()
#' @param threads maximum number of concurrent threads
#' @param memory primary workspace memory
#' @param results_dir
#' @param out_prefix
#' @param params_farm params_farm object name
#' @keywords plink2 score
#' @usage Plink19Clump(plink2_exec, bfile, q_score_range, score_col_nums,
#' score, threads, memory, out, params_farm)
#' @examples
#' PRSscore(plink2_exec = "plink2 ",
#'             bfile = bfile,
#'             score_col_nums = ncols,
#'             p_values = p_values,
#'             pthres = pthres,
#'             threads = 4,
#'             memory = 8000,
#'             results_dir = results_dir,
#'             params_farm = params_farm)

helper_score_loop <- function(plink2_exec,
                        bfile,
                        plink_list,
                        pthres,
                        threads,
                        memory,
                        results_dir,
                        out_prefix = as.null(),
                        params_farm = as.null()){
  if (is.null(params_farm)) {
    print("no params_farm")
  } else {
    print("params_farm list will be used")
    plink2_exec <- unlist(params_farm["mem"])
    memory <- as.character(unlist(params_farm["mem"]))
    threads <- as.character(unlist(params_farm["threads"]))
    pthres <- as.character(unlist(params_farm["pthres"]))
  }

  temp.dir <- paste0(results_dir,"temp/")
  if (is.null(out_prefix)) {
    print("not out_prefix")
    out.prefix <- ""
  } else {
    print(paste0("out_prefix: ", out_prefix))
    out.prefix <- paste0(out_prefix, "_")
  }
  this.scores <- plink_list[[1]]
  this.p_values <- plink_list[[2]]
  this.unique_infor <- plink_list[[3]]
  this.p_value_file <- as.character(unlist(plink_list["p_value_file"]))
  this.scores_file <- as.character(unlist(plink_list["scores_file"]))
  this.q_range_file <- as.character(unlist(plink_list["q_range_file"]))
  prs_p_other_ <- paste0(temp.dir, out.prefix, "prs_p_other_")
  this.pthres <- pthres
  assign("prs_p_other_", prs_p_other_, envir = .GlobalEnv)
  p_values_temp <- this.p_values

  for(k1 in 1:length(this.pthres)){
    #keep all the SNPs with P_EUR less than pthres[k1] in the analyses
    idx <- which(this.unique_infor$P_ref<=this.pthres[k1])
    print(paste0("pthres: ", this.pthres[k1]))
    print(paste0("length idx: ", length(idx)))
    p_values_temp$P[idx] <- 0
    print(paste0("writing ", this.p_value_file))
    write.table(p_values_temp,
                file = this.p_value_file,
                col.names = F,
                row.names = F,
                quote=F)
    score.col_nums <- ncol(this.scores)
    plink2score(params_farm = params_farm,
                plink2_exec = plink2_exec,
                bfile = bfile,
                q_range_file = this.q_range_file,
                p_value_file = this.p_value_file,
                scores_file = this.scores_file,
                score_col_nums = score.col_nums,
                results_dir = results_dir,
                pthres_idx = k1,
                threads = threads,
                out = prs_p_other_,
                memory = memory)
  }
  return(prs_p_other_)
}
