#' PRSscore
#'
#' Master function for scoring with plink2.
#' If additional options are required, please use the source() command
#' as demonstrated in the vignette.
#' @param plink2_exec Plink binary execute file. Default "plink2".
#' @param bfile prefix for target plink binary set (prefix.bed, prefix.bim, prefix.fam)
#' @param q_range_file File name and location of written q_range dataframe produced
#' by PreparePlinkfile(). By default PreparePlinkfile() names this 'q_range_file'
#' @param scores scores dataframe produced by PreparePlinkfile().
#' @param scores_file File name and location of written scores dataframe produced
#' by PreparePlinkfile(). By default PreparePlinkfile() names this 'scores_file'
#' @param p_values p_values dataframe produced by PreparePlinkfile()
#' @param pthres vector of p_value thresholds used to select snps for PRS.
#' Default vector name is 'pthres' which is generated by PreparePlinkfile()
#' @param threads maximum number of concurrent threads
#' @param memory primary workspace memory
#' @param out output folder and file prefix for Plink2. Default name prs_p_other_
#' <pthres column number>.<range name>.sscore
#' @param params_farm params_farm object name
#' @keywords plink2 score
#' @usage Plink19Clump(plink2_exec, bfile, q_score_range, score_col_nums,
#' score, threads, memory, out, params_farm)
#' @export
#' @examples
#' pthres <- c(5E-08,5E-07,5E-06,5E-05,5E-04,5E-03,5E-02,5E-01,1.0)
#'
#' PreparePlinkFile(snp_list = snp_list,
#'                  sum_com = sum_com,
#'                  pthres = pthres,
#'                  return_list = FALSE)
#'
#' prs_out <- paste0(temp.dir,"prs_p_other")
#' PRSscore(plink2_exec = "plink2 ",
#'             bfile = bfile,
#'             q_range_file = q_range_file,
#'             scores = scores,
#'             scores_file = scores_file,
#'             p_values = p_values,
#'             pthres = pthres,
#'             threads = 4,
#'             memory = 8000,
#'             out = prs_out,
#'             params_farm = params_farm)

PRSscore <- function(plink2_exec = "plink2 ",
                     bfile,
                     q_range_file = q_range_file,
                     scores = scores,
                     scores_file = scores_file,
                     p_values = p_values,
                     pthres = pthres,
                     threads = 4,
                     memory = 8000,
                     out = "prs_p_other",
                     params_farm=as.null()){

  if (is.null(params_farm)) {
    print("no params_farm")
  } else {
    print("params_farm list will be used")
    mem <- as.character(unlist(params_farm["mem"]))
    threads <- as.character(unlist(params_farm["threads"]))
  }

  n_col <- ncol(scores)
  helper_score_loop(plink2_exec,
                    bfile = bfile,
                    q_range_file = q_range_file,
                    score_col_nums = n_col,
                    scores_file = scores_file,
                    p_values = p_values,
                    pthres = pthres,
                    threads = 4,
                    memory = 8000,
                    out = out)
  prs_mat <- helper_combine_PRS(scores = scores,
                     pthres = pthres,
                     prs_file_prefix = out)
  return(prs_mat)
}
