#' PRSscore
#'
#' Master function for scoring with plink2.
#' If additional options are required, please use the source() command
#' as demonstrated in the vignette.
#' @param plink2_exec Plink binary execute file. Default "plink2".
#' @param bfile prefix for target plink binary set (prefix.bed, prefix.bim, prefix.fam)
#' @param scores scores dataframe produced by PreparePlinkfile().
#' by PreparePlinkfile(). By default PreparePlinkfile() names this 'scores_file'
#' @param p_values p_values dataframe produced by PreparePlinkfile()
#' @param pthres vector of p_value thresholds used to select snps for PRS.
#' Default vector name is 'pthres' which is generated by PreparePlinkfile()
#' @param threads maximum number of concurrent threads
#' @param memory primary workspace memory
#' @param params_farm params_farm object name
#' @keywords plink2 score
#' @usage Plink19Clump(plink2_exec, bfile, q_score_range, score_col_nums,
#' score, threads, memory, out, params_farm)
#' @export
#' @examples
#' pthres <- c(5E-08,5E-07,5E-06,5E-05,5E-04,5E-03,5E-02,5E-01,1.0)
#'
#' PreparePlinkFile(snp_list = snp_list,
#'                  sum_com = sum_com,
#'                  pthres = pthres,
#'                  return_list = FALSE)
#'
#' prs_out <- paste0(temp.dir,"prs_p_other")
#' PRSscore(plink2_exec = "plink2 ",
#'             bfile = bfile,
#'             q_range_file = q_range_file,
#'             scores = scores,
#'             scores_file = scores_file,
#'             p_values = p_values,
#'             pthres = pthres,
#'             threads = 4,
#'             memory = 8000,
#'             out = prs_out,
#'             params_farm = params_farm)

PRSscore <- function(plink2_exec = "plink2 ",
                     bfile,
                     plink_list,
                     pthres = c(5E-08,5E-07,5E-06,5E-05,5E-04,5E-03,5E-02,5E-01,1.0),
                     threads = 4,
                     memory = 8000,
                     results_dir,
                     out_prefix = as.null(),
                     params_farm=as.null()){

  if (is.null(params_farm)) {
    print("no params_farm")
  } else {
    print("params_farm list will be used")
    plink2_exec <- as.character(unlist(params_farm["plink2_exec"]))
    memory <- as.character(unlist(params_farm["mem"]))
    threads <- as.character(unlist(params_farm["threads"]))
    pthres <- as.character(unlist(params_farm["pthres"]))
  }

  this.plink2_exec <- plink2_exec
  this.bfile <- bfile
  this.pthres <- pthres
  this.threads <- threads
  this.memory <- memory
  this.results_dir <- results_dir
  this.out_prefix <- out_prefix
  this.params_farm <- params_farm
  this.plink_list <- plink_list

  prs_p_other_ <- helper_score_loop(plink2_exec = this.plink2_exec,
                                    bfile = this.bfile,
                                    pthres = this.pthres,
                                    threads = this.threads,
                                    memory = this.memory,
                                    plink_list = this.plink_list,
                                    results_dir = this.results_dir,
                                    out_prefix = this.out_prefix,
                                    params_farm = this.params_farm)
  this.scores <- this.scores <- plink_list[[1]]
  prs_mat <- helper_combine_PRS(scores = this.scores,
                                pthres = this.pthres,
                                prs_p_other_ = prs_p_other_
                                )
  assign("prs_mat", prs_mat, envir = .GlobalEnv)
  print("prs_mat object created")
}
