#' PRSscore
#'
#' Master function for scoring with plink2.
#' If additional options are required, please use the source() command
#' as demonstrated in the vignette.
#' @param plink2_exec Plink binary execute file. Default "plink2".
#' @param bfile prefix for target plink binary set (prefix.bed, prefix.bim, prefix.fam)
#' @param file_list description
#' @param pthres vector of p_value thresholds used to select snps for PRS.
#' Default vector name is 'pthres' which is generated by PreparePlinkfile()
#' @param threads plink parameter for maximum number of concurrent threads
#' @param memory plink parameter for primary workspace memory
#' @param results_dir Folder or directory to export files
#' @param out_prefix Prefix for exported files. Recommended when plink files
#' are divided by chromosome or chunks, i.e., "chr1" or "chr2", and CTSLEB
#' script is dispatched in parallel
#' @param params_farm params_farm object name
#' @export
#' @usage PRSscore(plink2_exec, bfile, plink_list, pthres, memory, out, params_farm)

PRSscore <- function(plink2_exec = "plink2 ",
                     bfile,
                     plink_list,
                     pthres = c(5E-08,5E-07,5E-06,5E-05,5E-04,5E-03,5E-02,5E-01,1.0),
                     threads = 4,
                     memory = 8000,
                     results_dir,
                     out_prefix = as.null(),
                     params_farm=as.null()){

  print("executing PRSscore()... ")
  if (is.null(params_farm)) {
    #print("no params_farm")
  } else {
   # print("params_farm list will be used")
    plink2_exec <- as.character(unlist(params_farm["plink2_exec"]))
    memory <- as.integer(unlist(params_farm["mem"]))
    threads <- as.integer(unlist(params_farm["threads"]))
    pthres <- as.numeric(unlist(params_farm["pthres"]))
  }

  plink2_exec <- plink2_exec
  bfile <- bfile
  pthres <- pthres
  threads <- threads
  memory <- memory
  results_dir <- results_dir
  out_prefix <- out_prefix
  params_farm <- params_farm
  plink_list <- plink_list

  prs_p_other_ <- helper_score_loop(plink2_exec = plink2_exec,
                                    bfile = bfile,
                                    pthres = pthres,
                                    threads = threads,
                                    memory = memory,
                                    plink_list = plink_list,
                                    results_dir = results_dir,
                                    out_prefix = out_prefix)
  scores <- plink_list[[1]]
  prs_mat <- helper_CombinePRS(scores = scores,
                                pthres = pthres,
                                prs_p_other_ = prs_p_other_)
  print("prs_mat object created")
  return(prs_mat)
}
